# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  lint: 
    docker:
      -image: cicleci/node:11
    steps:
      - checkout
      - run:
          name: Lint
          command: yarn lint
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/modelify-client

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - dependency-cache-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependency-cache-{{ checksum "package.json" }}


